[theme]
primaryColor = "#1e88e5"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#212121"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[browser]
gatherUsageStats = false
serverAddress = "localhost"